
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSleftTIMESEQ ID LPAREN NUM PLUS PRINT RPAREN TIMES\n    statements : statements statement\n    \n    statements : statement\n    \n    statement : ID EQ expr\n    \n    statement : PRINT LPAREN expr RPAREN\n    \n    expr : expr PLUS expr\n         | expr TIMES expr\n    \n    expr : NUM\n    \n    expr : ID\n    \n    expr : LPAREN expr RPAREN\n    '
    
_lr_action_items = {'ID':([0,1,2,5,6,7,8,9,10,11,13,14,16,17,18,19,],[3,3,-2,-1,8,8,-8,-3,-7,8,8,8,-4,-5,-6,-9,]),'PRINT':([0,1,2,5,8,9,10,16,17,18,19,],[4,4,-2,-1,-8,-3,-7,-4,-5,-6,-9,]),'$end':([1,2,5,8,9,10,16,17,18,19,],[0,-2,-1,-8,-3,-7,-4,-5,-6,-9,]),'EQ':([3,],[6,]),'LPAREN':([4,6,7,11,13,14,],[7,11,11,11,11,11,]),'NUM':([6,7,11,13,14,],[10,10,10,10,10,]),'PLUS':([8,9,10,12,15,17,18,19,],[-8,13,-7,13,13,-5,-6,-9,]),'TIMES':([8,9,10,12,15,17,18,19,],[-8,14,-7,14,14,14,-6,-9,]),'RPAREN':([8,10,12,15,17,18,19,],[-8,-7,16,19,-5,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'statement':([0,1,],[2,5,]),'expr':([6,7,11,13,14,],[9,12,15,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statements statement','statements',2,'p_statements_multiple','plydemo.py',50),
  ('statements -> statement','statements',1,'p_statements_single','plydemo.py',58),
  ('statement -> ID EQ expr','statement',3,'p_assignment_statement','plydemo.py',66),
  ('statement -> PRINT LPAREN expr RPAREN','statement',4,'p_print_statement','plydemo.py',74),
  ('expr -> expr PLUS expr','expr',3,'p_expr_binop','plydemo.py',82),
  ('expr -> expr TIMES expr','expr',3,'p_expr_binop','plydemo.py',83),
  ('expr -> NUM','expr',1,'p_expr_num','plydemo.py',90),
  ('expr -> ID','expr',1,'p_expr_name','plydemo.py',97),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','plydemo.py',104),
]
